version: "3.7"
services:
  web1:
    build: ./quote_gen
    ports:
      - "5010-5012:5000"
    volumes:
      - "./quote_gen:/app"
  web2:
    build: ./quote_disp
    ports:
      - "5020-5022:5001"
    depends_on:
      - web1
    volumes:
      - "./quote_disp:/app"